// <auto-generated />
using MVC_Viper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Viper.Migrations
{
    [DbContext(typeof(ProviderDBContext))]
    partial class ProviderDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billcall", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("Bill_ID");

                    b.Property<int>("CallId")
                        .HasColumnType("int")
                        .HasColumnName("Call_ID");

                    b.HasKey("BillId", "CallId")
                        .HasName("PK__billcall__6EF0120D4829D6D4");

                    b.HasIndex("CallId");

                    b.ToTable("billcalls", (string)null);
                });

            modelBuilder.Entity("MVC_Viper.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("Admin_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("AdminId")
                        .HasName("PK__admin__4A3006F74B196BEF");

                    b.HasIndex("UserId");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("MVC_Viper.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("Bill_ID");

                    b.Property<decimal?>("Costs")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BillId")
                        .HasName("PK__bills__CF6E7D4378E44C25");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("MVC_Viper.Models.Call", b =>
                {
                    b.Property<int>("CallId")
                        .HasColumnType("int")
                        .HasColumnName("Call_ID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("CallId")
                        .HasName("PK__calls__19E6F4EB2F82E63F");

                    b.ToTable("calls");
                });

            modelBuilder.Entity("MVC_Viper.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("Client_Id");

                    b.Property<string>("Afm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AFM");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("ClientId")
                        .HasName("PK__clients__75A5D8F8F69852E9");

                    b.HasIndex("UserId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("MVC_Viper.Models.Phone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Program_Name");

                    b.HasKey("PhoneNumber")
                        .HasName("PK__phones__85FB4E391C49890F");

                    b.HasIndex("ProgramName");

                    b.ToTable("phones");
                });

            modelBuilder.Entity("MVC_Viper.Models.Programs", b =>
                {
                    b.Property<string>("ProgramName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Program_Name");

                    b.Property<string>("Benefits")
                        .HasColumnType("text");

                    b.Property<decimal?>("Charge")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("ProgramName")
                        .HasName("PK__programs__1DF87844D749C4E7");

                    b.ToTable("programs");
                });

            modelBuilder.Entity("MVC_Viper.Models.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("Seller_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("SellerId")
                        .HasName("PK__sellers__009FC2A9AA606066");

                    b.HasIndex("UserId");

                    b.ToTable("sellers");
                });

            modelBuilder.Entity("MVC_Viper.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Property")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__users__206D917065CDFAD4");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Billcall", b =>
                {
                    b.HasOne("MVC_Viper.Models.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK__billcalls__Bill___4BAC3F29");

                    b.HasOne("MVC_Viper.Models.Call", null)
                        .WithMany()
                        .HasForeignKey("CallId")
                        .IsRequired()
                        .HasConstraintName("FK__billcalls__Call___4CA06362");
                });

            modelBuilder.Entity("MVC_Viper.Models.Admin", b =>
                {
                    b.HasOne("MVC_Viper.Models.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__admin__User_Id__3F466844");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Viper.Models.Bill", b =>
                {
                    b.HasOne("MVC_Viper.Models.Phone", "PhoneNumberNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("PhoneNumber")
                        .HasConstraintName("FK__bills__PhoneNumb__46E78A0C");

                    b.Navigation("PhoneNumberNavigation");
                });

            modelBuilder.Entity("MVC_Viper.Models.Client", b =>
                {
                    b.HasOne("MVC_Viper.Models.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__clients__User_Id__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Viper.Models.Phone", b =>
                {
                    b.HasOne("MVC_Viper.Models.Programs", "ProgramNameNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("ProgramName")
                        .HasConstraintName("FK__phones__Program___440B1D61");

                    b.Navigation("ProgramNameNavigation");
                });

            modelBuilder.Entity("MVC_Viper.Models.Seller", b =>
                {
                    b.HasOne("MVC_Viper.Models.User", "User")
                        .WithMany("Sellers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__sellers__User_Id__398D8EEE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Viper.Models.Phone", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("MVC_Viper.Models.Programs", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("MVC_Viper.Models.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Clients");

                    b.Navigation("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
